name: blogpub-go
on:
  push:
    branches:
      - main
    paths:
    - .github/workflows/blogpub-go.yml
    - '**/*.go'
    - go.mod
    - '!**/*.md'
  pull_request:
    paths:
    - .github/workflows/blogpub-go.yml
    - '**/*.go'
    - go.mod
    - '!**/*.md'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2

    - name: Test Go code
      run: go test ./... -v
